spring:
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/notesdb}
   # url: ${DB_URI:jdbc:postgresql://dbpostgresql:5432/notesdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     # ddl-auto: create
    properties:
      hibernate:
        id.new_generator_mappings: false
        show_sql: true
    open-in-view: false
    database: postgresql
  liquibase:
    enabled: true
    change-log: classpath:db-changelog/changelog.xml

management:
  endpoints.web.exposure.include: health,info
  health:
    mail:
      enabled: false
server:
  port: 8080
logging:
  level:
    root: DEBUG
